server.port=8080
spring.application.name=ehc-backend
spring.datasource.url=${EHC_DB_URL:jdbc:sqlserver://localhost:1433;databaseName=ehc_rites;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${EHC_DB_USER:ehc_rites_user}
spring.datasource.password=${EHC_DB_PASSWORD:password}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.sql.init.mode=never
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
